### ISSUE TITLE
Variation method calls don't add users in the dashboard

### ISSUE THREAD

**Issue by jsonmactal** [launchdarkly/apex-server-sdk#8]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/hc/en-us/requests/new) or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
Calling variation methods (boolVariation, stringVariation etc) from LDClient don't register uses to the dashboard. Tried adding users using identify method, this adds users on the dashboard.

**To reproduce**
Call methods `boolVariation` or `stringVariation` from LDClient and pass related flags and LDuser, make sure LDConfig `allAttributesPrivate` is false.

```
String flagKey = 'my-flag';

LDConfig config = new LDConfig.Builder()
                                .setAllAttributesPrivate(false)
                                .build();

LDUser user = new LDUser.Builder('123abc')
                .setFirstName('Rabbit')
                .setLastName('Bunny')
                .setEmail('rabbitbunny@testdfgd1.com')
                .build();

if (client.boolVariation(user, flagKey, false)) {
    System.debug('feature is on');
} else {
    System.debug('feature is off');
}
```

**Expected behavior**
Users are added on the dashboard when calling a variation method.

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
apex-server-sdk 1.1.0

**Language version, developer tools**
go version go1.17.1 windows/amd64

**OS/platform**
Windows 10
Salesforce Developer Edition (Winter 22)

**Additional context**

**Comment by jsonmactal** [comment]
@louis-launchdarkly , thanks for this clarification

**Comment by cwaldren-ld** [comment]
Closing this issue as the documentation was updated [here](https://docs.launchdarkly.com/sdk/features/identify#apex). Thanks again @jsonmactal for reporting it.
